In [ ]:
import torch
import numpy as np
print(torch.__version__)

2.5.1+cu121


### Creating Tensors

In [2]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
print(f'Scalar tensor dimentions: {scalar.ndim}, Getting item out of the tensor: {scalar.item()}')

Scalar tensor dimentions: 0, Getting item out of the tensor: 7


In [4]:
# Vector 
vector = torch.tensor([1, 3])
vector

tensor([1, 3])

In [5]:
vector.shape, vector.ndim


(torch.Size([2]), 1)

In [6]:
# Matrix

matrix = torch.tensor([
    [1, 3, 4],
    [1, 2, 4]
])
matrix

tensor([[1, 3, 4],
        [1, 2, 4]])

In [7]:
matrix.ndim, matrix.shape

(2, torch.Size([2, 3]))

In [8]:
# TENSOR 

TENSOR = torch.tensor([
    [
        [1, 2, 3],
        [2, 3, 4],
        [1, 4, 5]
    ]
])
TENSOR

tensor([[[1, 2, 3],
         [2, 3, 4],
         [1, 4, 5]]])

In [9]:
TENSOR.ndim, f'3D shape tensor - {TENSOR.shape}'

(3, '3D shape tensor - torch.Size([1, 3, 3])')

### Random Tensors

why random tensors?

The way that Neural Network learn is that they start with tensors full of random values and adjust those random numbers to represent the data better 

`Start with random nums -> look at data -> update random numbers -> repeat till some condition or desired output`

In [10]:
# Creating Random Tensors 

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6715, 0.9857, 0.3622, 0.8019],
        [0.8880, 0.4519, 0.8391, 0.7249],
        [0.5592, 0.5806, 0.5827, 0.1724]])

In [11]:
# Creating random image tensors with the size of image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channel 

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones Tensors 

In [12]:
# Tensor of zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
# Tensor of ones
ones = torch.ones(size=(4, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
ones.dtype

torch.float32

### Creating Tensor's range and Tensors-like

In [16]:
# Range Tensor

range_tensor = torch.arange(start=11, step=22, end=121)
range_tensor

tensor([11, 33, 55, 77, 99])

In [17]:
# Creating Tensor-like

range_tensor_like = torch.zeros_like(range_tensor)
range_tensor_like

tensor([0, 0, 0, 0, 0])

### Tensor Dtypes

In [37]:
dtype_tensor = torch.tensor(
    [1.0, 3.0, 8.0],
    dtype=torch.float16,
    device=None, # what device is our tensor on
    requires_grad=False # whether or not to track a gradients with this tensor operations
)
dtype_tensor

tensor([1., 3., 8.], dtype=torch.float16)

In [38]:
float_32_tensor = dtype_tensor.type(torch.float32)

In [39]:
float_32_tensor * dtype_tensor

tensor([ 1.,  9., 64.])

### Matrix Manipulation

In [9]:
tensor = torch.tensor([1, 2, 3])
tensor + 10, torch.add(tensor, 10)

(tensor([11, 12, 13]), tensor([11, 12, 13]))

In [10]:
# Multiplication

tensor * 10, torch.mul(tensor, tensor)

(tensor([10, 20, 30]), tensor([1, 4, 9]))

In [6]:
# substract 

tensor - 10

tensor([-9, -8, -7])

In [16]:
# Matrix Multiplication - Dot product

tensor_1 = torch.tensor([
    [1, 2, 3],
    [5, 3, 6],
    [12, 3, 4]
])
tensor_1 * tensor_1


tensor([[  1,   4,   9],
        [ 25,   9,  36],
        [144,   9,  16]])

In [ ]:
# %%time

# Matrix Multiplication - Cross Product
torch.matmul(tensor_1, tensor_1)

CPU times: total: 0 ns
Wall time: 0 ns


tensor([[47, 17, 27],
        [92, 37, 57],
        [75, 45, 70]])

In [ ]:
# %%time

len(tensor_1)

res_tensor = torch.zeros(len(tensor_1), len(tensor_1))

for i in range(len(tensor_1)):
    for j in range(len(tensor_1[0])):
        for k in range(len(tensor_1)):
            res_tensor[i][j] += tensor_1[i][k] * tensor_1[k][j]

print(res_tensor)

tensor([[47., 17., 27.],
        [92., 37., 57.],
        [75., 45., 70.]])
CPU times: total: 0 ns
Wall time: 1e+03 μs


### Finding MAX, MIN, MEAN, SUM etc (tensor Aggregation)

In [43]:
# Create a tensor

x = torch.arange(start=21, step=21, end=234)

x.dtype

torch.int64

In [46]:
# Finding max, min, mean, sum

x.max(), x.min(), x.type(torch.float32).mean(), x.sum()



(tensor(231), tensor(21), tensor(126.), tensor(1386))

In [50]:
# position of MIN and MAX

x.argmin(), x.argmax()

(tensor(0), tensor(10))

### Reshaping, Stacking, squeezing, unsqueezing tensors 

* Reshaping Tensor - reshapes an input tensor to a defined shape
* View - Returns of a view of an input tensor which shares the same memory
* Stacking - Concatenates the tensors on top of each other (**Vstack**) or side by side (**Hstack**)
* Squeeze - remove all `1` dimentions from a tensor
* Unsqueeze - add a `1` dimention to a target tensor
* Commute - return a view of a input with dimentions permuted(swapped) in a certain way

In [60]:
x = torch.arange(1., 11.)

x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [62]:
# reshape

x.reshape((2, 5))

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [64]:
# change the view 

z = x.view(1, 10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [74]:
# Stack tensors on top of each other 

x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [83]:
# Squeeze - removes the all the single dimentions from (1, 223, 323) -> (223, 323)

x_squeezed = torch.squeeze(x)
x_squeezed

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [84]:
# unsqueeze - adds a single dimention to a target tensor

x_unsqueezed = torch.unsqueeze(x, dim=1)
x_unsqueezed

tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])

In [88]:
# torch.permute - rearranges the dimentions of a target tensor in specified order 

x_original = torch.rand(size=(224, 224, 3)) # [height, width, color-channel]

# Permute 
x_permuted = x_original.permute(2, 0, 1) # shifts axis  0->1, 1->2, 2->0

x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

### Indexing in Tensors

In [ ]:
import torch

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [13]:
x[0][1]

tensor([4, 5, 6])

### PyTorch Tensors and Numpy

In [16]:
# Numpy to Tensor

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [17]:
# Tensor to Numpy

tensor = torch.ones(10).reshape(2, 5)
n_tensor = tensor.numpy()

tensor, n_tensor

(tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=float32))

### Random Seed

In [20]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_a = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_b = torch.rand(3, 4)

random_a, random_b

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))